[package]
edition.workspace = true
license.workspace = true
name = "EfficiencyCode-plugin"
version.workspace = true

[lib]
doctest = false
name = "EfficiencyCode_plugin"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
EfficiencyCode-config = { workspace = true }
EfficiencyCode-protocol = { workspace = true }
EfficiencyCode-utils-absolute-path = { workspace = true }
EfficiencyCode-utils-path-uri = { workspace = true }
EfficiencyCode-utils-plugins = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
