[package]
edition.workspace = true
license.workspace = true
name = "EfficiencyCode-analytics"
version.workspace = true

[lib]
doctest = false
name = "EfficiencyCode_analytics"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
EfficiencyCode-app-server-protocol = { workspace = true }
EfficiencyCode-git-utils = { workspace = true }
EfficiencyCode-login = { workspace = true }
EfficiencyCode-model-provider = { workspace = true }
EfficiencyCode-plugin = { workspace = true }
EfficiencyCode-protocol = { workspace = true }
EfficiencyCode-state = { workspace = true }
os_info = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha1 = { workspace = true }
tokio = { workspace = true, features = [
    "macros",
    "rt-multi-thread",
] }
tracing = { workspace = true, features = ["log"] }

[dev-dependencies]
EfficiencyCode-utils-absolute-path = { workspace = true }
pretty_assertions = { workspace = true }
