load("//:defs.bzl", "EfficiencyCode_rust_crate")

EfficiencyCode_rust_crate(
    name = "skills",
    compile_data = glob(
        include = ["**"],
        allow_empty = True,
        exclude = [
            "**/* *",
            "BUILD.bazel",
            "Cargo.toml",
        ],
    ),
    crate_name = "EfficiencyCode_skills",
)
