// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EfficiencyCodeErrorInfo } from "./EfficiencyCodeErrorInfo";

export type TurnError = { message: string, efficiencyCodeErrorInfo: EfficiencyCodeErrorInfo | null, additionalDetails: string | null, };
