[package]
edition.workspace = true
license.workspace = true
name = "EfficiencyCode-core-api"
version.workspace = true

[lib]
doctest = false
name = "EfficiencyCode_core_api"
path = "src/lib.rs"
test = false

[lints]
workspace = true

[dependencies]
EfficiencyCode-app-server-protocol = { workspace = true }
EfficiencyCode-arg0 = { workspace = true }
EfficiencyCode-analytics = { workspace = true }
EfficiencyCode-config = { workspace = true }
EfficiencyCode-core = { workspace = true }
EfficiencyCode-extension-api = { workspace = true }
EfficiencyCode-home = { workspace = true }
EfficiencyCode-history = { workspace = true }
EfficiencyCode-image-generation-extension = { workspace = true }
EfficiencyCode-exec-server = { workspace = true }
EfficiencyCode-features = { workspace = true }
EfficiencyCode-login = { workspace = true }
EfficiencyCode-model-provider-info = { workspace = true }
EfficiencyCode-models-manager = { workspace = true }
EfficiencyCode-protocol = { workspace = true }
EfficiencyCode-state = { workspace = true }
EfficiencyCode-utils-absolute-path = { workspace = true }
